apiVersion: apps/v1
kind: Deployment
metadata:
  name: compliant-app
  namespace: app-team
  labels:
    app.kubernetes.io/name: compliant-app
    app.kubernetes.io/managed-by: lab-02
spec:
  replicas: 1
  selector:
    matchLabels:
      app: compliant-app
      role: frontend
  template:
    metadata:
      labels:
        app: compliant-app
        role: frontend
    spec:
      automountServiceAccountToken: false
      securityContext:
        runAsNonRoot: true
        runAsUser: 65534
        fsGroup: 65534
        seccompProfile:
          type: RuntimeDefault
      containers:
        - name: app
          image: nginx:1.25-alpine
          ports:
            - containerPort: 8080
          securityContext:
            allowPrivilegeEscalation: false
            readOnlyRootFilesystem: true
            capabilities:
              drop:
                - ALL
          resources:
            limits:
              memory: "128Mi"
              cpu: "200m"
            requests:
              memory: "64Mi"
              cpu: "100m"
          livenessProbe:
            httpGet:
              path: /healthz
              port: 8080
            initialDelaySeconds: 5
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /ready
              port: 8080
            initialDelaySeconds: 3
            periodSeconds: 5
