apiVersion: apps/v1
kind: Deployment
metadata:
  name: attack-simulator
  namespace: lab-runtime
  labels:
    app: attack-simulator
spec:
  replicas: 1
  selector:
    matchLabels:
      app: attack-simulator
  template:
    metadata:
      labels:
        app: attack-simulator
    spec:
      containers:
        - name: attacker
          image: ubuntu:22.04
          command:
            - /bin/bash
            - -c
            - |
              apt-get update && apt-get install -y curl netcat-openbsd nmap procps && sleep infinity
          resources:
            limits:
              memory: "256Mi"
              cpu: "200m"
